# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[mgr]
cwd = { fg = "#c1c3c4" }

# Hovered
hovered         = { reversed = true }
preview_hovered = { underline = false }

# Find
find_keyword  = { fg = "#06ea61", bold = true, italic = true, underline = true }
find_position = { fg = "#ea5ce2", bg = "reset", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#c9d364", bg = "#c9d364" }
marker_cut      = { fg = "#ff6865", bg = "#ff6865" }
marker_marked   = { fg = "#c1c3c4", bg = "#c1c3c4" }
marker_selected = { fg = "#06ea61", bg = "#06ea61" }

# Count
count_copied   = { fg = "#282a36", bg = "#c9d364" }
count_cut      = { fg = "#282a36", bg = "#ff6865" }
count_selected = { fg = "#282a36", bg = "#06ea61" }

# Border
border_symbol = " "
border_style  = { fg = "#7282b5" }

# : }}}


# : Tabs {{{

[tabs]
active   = { fg = "#282a36", bg = "#ea5ce2", bold = true }
inactive = { fg = "#ea5ce2", bg = "#44475a" }

# : }}}


# : Mode {{{

[mode]

normal_main = { fg = "#282a36", bg = "#ff6865", bold = true }
normal_alt  = { fg = "#ea5ce2", bg = "#44475a" }

# Select mode
select_main = { fg = "#282a36", bg = "#ea5ce2", bold = true }
select_alt  = { fg = "#c1c3c4", bg = "#44475a" }

# Unset mode
unset_main = { fg = "#282a36", bg = "#ffb86c", bold = true }
unset_alt  = { fg = "#ffb86c", bg = "#44475a" }

# : }}}


# : Status bar {{{

[status]
# Permissions
perm_sep   = { fg = "#7282b5" }
perm_type  = { fg = "#ea5ce2" }
perm_read  = { fg = "#06ea61" }
perm_write = { fg = "#ff6865" }
perm_exec  = { fg = "#c9d364" }

# Progress
progress_label  = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#ea5ce2", bg = "#63667d" }
progress_error  = { fg = "#ea5ce2", bg = "#ff6865" }

overall   = {}
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }


# : }}}


# : Pick {{{

[pick]
border   = { fg = "#ea5ce2" }
active   = { fg = "#ea5ce2", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "#ea5ce2" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[cmp]
border = { fg = "#ea5ce2" }

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#ea5ce2" }
title   = {}
hovered = { fg = "#ea5ce2", bold = true }

# : }}}


# : Which {{{

[which]
# mask            = { bg = "#44475a" }
cand            = { fg = "#c1c3c4" }
rest            = { fg = "#8998c9" }
desc            = { fg = "#ea5ce2" }
separator       = "  "
separator_style = { fg = "#83869c" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#c1c3c4" }
run     = { fg = "#ea5ce2" }
hovered = { reversed = true, bold = true }
footer  = { fg = "#44475a" }

# : }}}


# : Spotter {{{

[spot]
border   = { fg = "#ea5ce2" }
title    = { fg = "#ea5ce2" }
tbl_col  = { fg = "#c1c3c4" }
tbl_cell = { fg = "#ea5ce2" }

# : }}}


# : Notification {{{

[notify]
title_info  = { fg = "#c9d364" }
title_warn  = { fg = "#06ea61" }
title_error = { fg = "#ff6865" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Image
	{ mime = "image/*", fg = "#c1c3c4" },
	# Media
	{ mime = "{audio,video}/*", fg = "#06ea61" },
	# Archive
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#ea5ce2" },
	# Document
	{ mime = "application/{pdf,doc,rtf}", fg = "#c9d364" },
	# Virtual file system
	{ mime = "vfs/*", fg = "#8998c9" },
	# Fallback
	{ url = "*", fg = "#f8f8f2" },
	{ url = "*/", fg = "#ea5ce2" },
	# TODO: remove
	{ name = "*", fg = "#f8f8f2" },
	{ name = "*/", fg = "#ea5ce2" }
]

# : }}}
